base_address: "411 Fairchild Dr, Mountain View, CA"
search_radius_miles: 8
min_ratings_source: 100
google_maps_api_key: "AIzaSyC3zM1BAEa7A8KrlY5s4KTD7soB-Jtv4Nk"
search_keywords: [
    "sushi",
    "pizza",
    "mexican food",
    "cafe",
    "thai food",
    "indian food",
    "chinese food",
    "italian food",
    "vietnamese food",
    "korean bbq",
    "burgers",
    "seafood",
    "steakhouse",
    "vegetarian",
    "vegan restaurant",
    "bakery",
    "breakfast spot",
    "brunch",
    "ramen",
    "tacos",
    "gastropub",
    "diner",
    "french cuisine",
    "mediterranean food",
    "ethiopian restaurant",
    # ...and so on
  ]
